// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class change_Username_to_AgencyName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_Username_to_AgencyName));
        
        string IMigrationMetadata.Id
        {
            get { return "202412111903454_change_Username_to_AgencyName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
