// <auto-generated />
namespace RedHorseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class change_nullable_datetime_to_non_nullable_datetime_CreatedDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_nullable_datetime_to_non_nullable_datetime_CreatedDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202412111816288_change_nullable_datetime_to_non_nullable_datetime_CreatedDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
